language: node_js
services:
  - docker
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- npm install -g npm@5.2.0
- greenkeeper-lockfile-update
- npm prune
after_script:
- greenkeeper-lockfile-upload
after_success:
- ./deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
